// frontend/src/components/atoms/RadialSymbol.vue
<script setup>
/**
 * RadialSymbol - Symbole décoratif radial
 * Design System: Phenom Search
 */

defineOptions({ name: 'RadialSymbol' })

const props = defineProps({
  size: {
    type: Number,
    default: 200
  },
  rays: {
    type: Number,
    default: 24
  },
  color: {
    type: String,
    default: '#00F0FF'
  },
  opacity: {
    type: Number,
    default: 0.2
  }
})

// Générer les rayons
const rayPaths = computed(() => {
  const paths = []
  const centerX = props.size / 2
  const centerY = props.size / 2
  const innerRadius = props.size * 0.15
  const outerRadius = props.size * 0.45
  
  for (let i = 0; i < props.rays; i++) {
    const angle = (i * 2 * Math.PI) / props.rays - Math.PI / 2
    const x1 = centerX + innerRadius * Math.cos(angle)
    const y1 = centerY + innerRadius * Math.sin(angle)
    const x2 = centerX + outerRadius * Math.cos(angle)
    const y2 = centerY + outerRadius * Math.sin(angle)
    
    paths.push(`M ${x1} ${y1} L ${x2} ${y2}`)
  }
  
  return paths
})
</script>

<template>
  <svg
    :width="size"
    :height="size"
    :viewBox="`0 0 ${size} ${size}`"
    fill="none"
    :style="{ opacity }"
  >
    <!-- Center circle -->
    <circle
      :cx="size / 2"
      :cy="size / 2"
      :r="size * 0.1"
      :stroke="color"
      stroke-width="1"
      fill="none"
    />
    
    <!-- Rays -->
    <path
      v-for="(path, index) in rayPaths"
      :key="index"
      :d="path"
      :stroke="color"
      stroke-width="1"
      stroke-linecap="round"
    />
    
    <!-- Outer circle -->
    <circle
      :cx="size / 2"
      :cy="size / 2"
      :r="size * 0.48"
      :stroke="color"
      stroke-width="0.5"
      fill="none"
    />
  </svg>
</template>

// docs/PhenomSearch-react-code/Phenom Search Prototype/src/components/RadialSymbol.tsx
interface RadialSymbolProps {
  size?: number;
  className?: string;
  rays?: number;
}

export default function RadialSymbol({ size = 200, className = '', rays = 24 }: RadialSymbolProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 200 200"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
    >
      <g transform="translate(100, 100)">
        {Array.from({ length: rays }).map((_, i) => {
          const angle = (i * 360) / rays;
          const radians = (angle * Math.PI) / 180;
          const innerRadius = 30;
          const outerRadius = 90;
          const x1 = Math.cos(radians) * innerRadius;
          const y1 = Math.sin(radians) * innerRadius;
          const x2 = Math.cos(radians) * outerRadius;
          const y2 = Math.sin(radians) * outerRadius;
          
          return (
            <line
              key={i}
              x1={x1}
              y1={y1}
              x2={x2}
              y2={y2}
              stroke="currentColor"
              strokeWidth="1.5"
              strokeLinecap="round"
            />
          );
        })}
      </g>
    </svg>
  );
}
